apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: configdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  storageClassName: manual 
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 256Mi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configdb 
spec:
  storageClassName: manual 
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 128Mi 

---
apiVersion: v1
kind: Pod 
metadata:
  name: some-mongo  
  labels:
spec:
      containers:
        - name: some-mongo 
          image: lowdef/rpi3-mongodb3.2
          ports:
            - containerPort: 27017
            - containerPort: 28017
          command:
            - mongod
            - "--storageEngine"
            - "mmapv1"
          volumeMounts:
            - name: data 
              mountPath: /data/db
            - name: configdb 
              mountPath: /data/configdb
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: configdb
          persistentVolumeClaim:
            claimName: configdb 
