apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: configdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  storageClassName: manual
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configdb
spec:
  storageClassName: manual
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: db-sevice
  labels:
    name: db-service
    context: tmf640
spec:
  ports:
    - name: api
      port: 27017
    - name: query
      port: 28017
  selector:
    name: db-rc-pod
    context: tmf640
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: db-rc
  labels:
    name: db-rc
    context: tmf640
spec:
  replicas: 1
  template:
    metadata:
      name: db-rc-pod
      labels:
        name: db_rc-pod
        context: tmf640
    spec:
      containers:
        - name: db
          image: lowdef/rpi3-mongodb3.2
          ports:
            - containerPort: 27017
            - containerPort: 28017
          command:
            - mongod
            - "--storageEngine"
            - "mmapv1"
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: configdb
              mountPath: /data/configdb
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: configdb
          persistentVolumeClaim:
            claimName: configdb
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
  labels:
    name: web-rc
    context: tmf640
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web-rc-pod
        context: tmf640
    spec:
      containers:
        - name: web-rc-pod
          image: master1qr/tm-640-node
          ports:
            - containerPort: 8080
