apiVersion: v1
kind: services
metadata:
  name: db
  labels:
    name: db-service
    context: tmf640
spec:
  ports:
    - port: 27017
    - port: 28017
selector:
  name: db-rc-pod
  context: tmf640
----
apiVersion: v1
kind: ReplicationController
metadata:
  name: db-rc
  labels:
    name: db-rc
    context: tmf640
spec:
  replicas: 1
  template:
    metadata:
      name: db-rc-pod
      labels:
        name: db_rc-pod
        context: tmf640
    spec:
      containers:
        - name: db-rc-pod
          image: lowdef/rpi3-mongodb3.2
          ports:
            - containerPort: 27017
            - containerPort: 28017
----
apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
  labels:
    name: web-rc
    context: tmf640
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web-rc-pod
        context: tmf640
    spec:
      containers:
        - name: web-rc-pod
          image: master1qr/tm-640-node
          ports:
            - containerPort: 8080
